### ISSUE TITLE
Harverster running from last to first block by default.

### ISSUE THREAD

**Issue by derfredy** [Colm3na/polkastats-backend-v3#3]
It is interesting to change the actual behaviour and start harvesting from the lastest blocks first.
Thus, in a future, we will start serving fresh data first in our api.

**Comment by derfredy** [comment]
Maybe one of this harvester goal in the future would be to process runtime changes.
By now it would be enough to log the changes to the console.

**Comment by mariopino** [comment]
> Maybe one of this harvester goal in the future would be to process runtime changes.
> By now it would be enough to log the changes to the console.

Agree! I want to document it on the crawler code, thanks to the conversation with @jacogr

**Comment by mariopino** [comment]
Fixed by #29
