### ISSUE TITLE
Docker for phragmen crawler, sub task for ISSUE #8

### ISSUE THREAD

**Issue by derfredy** [Colm3na/polkastats-backend-v3#35]
Create dockers for phragmen

**Comment by derfredy** [comment]
The docker service is finished. We are just waiting for a phragmen binary that works.

**Comment by mariopino** [comment]
> The docker service is finished. We are just waiting for a phragmen binary that works.
> 
> Current container log says this:
> internal/modules/cjs/loader.js:796
> throw err;
> ^
> 
> Error: Cannot find module 'mysql2/promise'
> Require stack:
> 
> * /usr/app/polkastats-backend-v3/crawlers/phragmen.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
>   at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>   at Module.require (internal/modules/cjs/loader.js:848:19)
>   at require (internal/modules/cjs/helpers.js:74:18)
>   at Object. (/usr/app/polkastats-backend-v3/crawlers/phragmen.js:6:15)
>   at Module._compile (internal/modules/cjs/loader.js:955:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
>   at Module.load (internal/modules/cjs/loader.js:811:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:723:14)
>   at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/usr/app/polkastats-backend-v3/crawlers/phragmen.js' ]
>   }

mmm weird the mysql2 lib is not is the crawler source, can you please try again?

Also, I uploaded the old working version of offline-phragmen:

http://polkastats.io/downloads/mario-offline-phragmen.tar.gz

**Comment by derfredy** [comment]
Docker stuff already done. 
We'll continue on issue #8
