### ISSUE TITLE
Develop active accounts crawler

### ISSUE THREAD

**Issue by mariopino** [Colm3na/polkastats-backend-v3#7]
I think we can keep this **synchronous** by the moment (update data every 10min). So only one crawler is needed.

Reference:

https://github.com/Colm3na/polkastats-backend-v2/blob/master/crawlers/account.js

**Comment by derfredy** [comment]
I have tested the crawler with docker-compose environment and it seems to work. It is saving some accounts in the postgres db as expected.
I am not sure what is the best console log for crawler. We could try to log to console just when a new entry have been added to the db.

I have uncomented this line and it is too much logs..
console.log(`Processing account ${accountId}`);
