### ISSUE TITLE
Upload compiled offline-phragmen to the same forked repo

### ISSUE THREAD

**Issue by derfredy** [Colm3na/polkastats-backend-v3#76]
We should upload a compiled version of phragmen binary somewhere as it causes a lot of time lose each time we rebuild from scratch. 

What do you think it is a good place for it?
@Bigomby  @mariopino  @Scriptonita @Bitcoinera

**Comment by derfredy** [comment]
I suggest to upload it directly here:
https://github.com/Bigomby/offline-phragmen

**Comment by mariopino** [comment]
> I suggest to upload it directly here:
> https://github.com/Bigomby/offline-phragmen

100% agree!

**Comment by derfredy** [comment]
The PR is done.  @Bigomby  would you merge it to your repo?

Next step would be to modify the Dockerfile to download instead of a build. But I would leave the building code commented out just in case we need to compile updates in the future.

**Comment by Bigomby** [comment]
Here is the link to the compiled binary https://github.com/Bigomby/offline-phragmen/releases/tag/0.1.0
