### ISSUE TITLE
Develop rewards / slashes crawlers

### ISSUE THREAD

**Issue by mariopino** [Colm3na/polkastats-backend-v3#9]
We need to figure out how to fetch/calculate rewards and slashes.

Reference:

https://github.com/Colm3na/polkastats-backend-v2/blob/master/crawlers/rewards.js

**Comment by derfredy** [comment]
The crawler seems to work. Not sure, but the rewards are calculated "per epoch" ?¿  so the crawler probably needs to slow down its queries.

![image](https://user-images.githubusercontent.com/23276270/75118270-fda90c00-5678-11ea-87b4-80d34867fca7.png)

On the other hand, the SQL does not follows the same naming that previous tables. There is an extra "_info"  in table name.

**Comment by Bitcoinera** [comment]
> On the other hand, the SQL does not follows the same naming than previous tables. There is an extra "_info" in table name.

OK, I will change the table name as well as the query frequency (from session to epoch)

**Comment by derfredy** [comment]
To finish this we'll need:
- [ ] Switch from session index to epoch index
- [ ] Store only relevant data for calculations

Am I right?  @Bitcoinera @mariopino

**Comment by mariopino** [comment]
> To finish this we'll need:
> 
> * [ ]  1. Switch from session index to epoch index
> * [ ]  2. Store only relevant data for calculations
> 
> Am I right? @Bitcoinera @mariopino
> 
> Ift that is the case I would love some discusion about point 2.

Sorry for late response @derfredy , point 1 is not needed as is the exact same thing.

For 2 @Bitcoinera is inserting the data correctly as I see in the code IMO, but I could not test it cause a weird error in this poller.

**Comment by mariopino** [comment]
We need to add slashes, which I think we can get from system events (PolkaScan by now).

**Comment by Bitcoinera** [comment]
> but I could not test it cause a weird error in this poller.

What error are you experiencing? Still not storing correctly in the DB for you?

**Comment by Bitcoinera** [comment]
Should we close this issue now?
